import "./globals.css";
import { Sen } from "next/font/google";
import { cn } from "@/lib/utils";
import Providers from "../lib/Providers";

const sen = Sen({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-sen",
});

export const metadata = {
  title: "Warranty Pass V2.0",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn("bg-white text-slate-900 antialiased", sen.className)}
    >
      <body className="min-h-screen bg-slate-50 dark:bg-[rgb(3,7,17)] antialiased">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
