import "../../globals.css";
import { Sen } from "next/font/google";
import { cn } from "@/lib/utils";
import Providers from "@/lib/Providers";
import Navbar from "@/app/components/Navbar";

const sen = Sen({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-sen",
});

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className={cn("bg-white antialiased", sen.className)}>
      <div className="min-h-screen bg-slate-50 dark:bg-[rgb(3,7,17)] antialiased">
        <Providers>
          {/* @ts-expect-error Server Component */}
          <Navbar />
          {children}
        </Providers>
      </div>
    </main>
  );
}
